
```{r}
library(tidyverse)
```


#### Quantile-based measures
$$
s_1=\displaystyle\frac{Q_3+Q_1-2Q_2}{Q_3-Q_1}
$$


#### Groeneveld and Meeden's coefficient
$$
s_2=\displaystyle\frac{(\mu-\nu)}{E(|X-\nu|)}
$$

### alínea a)

```{r}
gerar_amostras <- function(n_amostras, dimensao_de_cada_amostra, seed = 2023) {
  set.seed(seed)
  df <- dimensao_de_cada_amostra
  matrix(rt(n = n_amostras * dimensao_de_cada_amostra, df = df), nrow = dimensao_de_cada_amostra)
}

amostras_i   <- gerar_amostras(100, 20)
amostras_ii  <- gerar_amostras(100, 100)
amostras_iii <- gerar_amostras(100, 1000)
```

### alínea b)

```{r}
estim.s1 <- function(x){
  Q1 <- quantile(x, 0.25)
  Q2 <- quantile(x, 0.5)
  Q3 <- quantile(x, 0.75)
  (Q3+Q1-2*Q2)/(Q3-Q1)
}

estim.s2 <- function(x){
  miu <- mean(x)
  nu <- median(x)
  (miu - nu)/mean(abs(x - nu))
}

amostras_i.s1   <- apply(amostras_i,   2, estim.s1)
amostras_i.s2   <- apply(amostras_i,   2, estim.s2)
amostras_ii.s1  <- apply(amostras_ii,  2, estim.s1)
amostras_ii.s2  <- apply(amostras_ii,  2, estim.s2)
amostras_iii.s1 <- apply(amostras_iii, 2, estim.s1)
amostras_iii.s2 <- apply(amostras_iii, 2, estim.s2)

# boxplot with all of these
boxplot(
  amostras_i.s1, amostras_i.s2,
  amostras_ii.s1, amostras_ii.s2,
  amostras_iii.s1, amostras_iii.s2,
  names = c("100x20 s1", "100x20 s2", "100x100 s1", "100x100 s2", "100x1000 s1", "100x1000 s2")
)

```


```{r}
# ggplot boxplot with facet_wrap
set.seed(2023)
df <- tibble(
  estimado = c(amostras_i.s1, amostras_i.s2, amostras_ii.s1, amostras_ii.s2, amostras_iii.s1, amostras_iii.s2),
  estimador = c(rep("s1", length( amostras_i.s1)),
                rep("s2", length( amostras_i.s2)),
                rep("s1", length(amostras_ii.s1)),
                rep("s2", length(amostras_ii.s2)),
                rep("s1", length(amostras_iii.s1)),
                rep("s2", length(amostras_iii.s2))),
  n_amostras_x_dimensao = c(rep("100x20", length(amostras_i.s1)),
                            rep("100x20", length(amostras_i.s2)),
                            rep("100x100", length(amostras_ii.s1)),
                            rep("100x100", length(amostras_ii.s2)),
                            rep("100x1000", length(amostras_iii.s1)),
                            rep("100x1000", length(amostras_iii.s2)))
)
ggplot(df, aes(x = estimador, y = estimado)) +
  geom_boxplot(aes(fill = estimador), alpha=0.6) + 
  geom_jitter(color="black", size=0.7, alpha=0.9) +
  scale_fill_manual(values=c("#F73859", "#404B69")) +
  facet_wrap(~ n_amostras_x_dimensao) + 
  labs(
    title = "Boxplot dos estimadores s1 e s2",
  )
```


### alínea c)

```{r}
mse <- function(predicted, actual) {
  # actual aqui e so um valor
  sum((predicted - actual)^2) / length(predicted)
}

# skewness of t student is 0 for df > 3

df <- data.frame(
  `n_amostras x dimensao` = c("100x20", "100x100", "100x1000"),
  `Erro padrão de s_1` = c(sd(amostras_i.s1) %>% round(3), sd(amostras_ii.s1) %>% round(3), sd(amostras_iii.s1) %>% round(3)),
  `Erro padrão de s_2` = c(sd(amostras_i.s2) %>% round(3), sd(amostras_ii.s2) %>% round(3), sd(amostras_iii.s2) %>% round(3)),
  `Erro quadrático médio de s_1` = c(mse(amostras_i.s1, 0) %>% round(3), mse(amostras_ii.s1, 0) %>% round(3), mse(amostras_iii.s1, 0) %>% round(3)),
  `Erro quadrático médio de s_2` = c(mse(amostras_i.s2, 0) %>% round(3), mse(amostras_ii.s2, 0) %>% round(3), mse(amostras_iii.s2, 0) %>% round(3))
)
df
```

Em todas as situações, o estimador $s_2$ apresenta um erro menor que o estimador $s_1$. Isso significa que o estimador $s_2$ é melhor a estimar a assimetria da distribuição t de Student quando esta apresenta $\nu = n$
