```{r packages}
# rm(list = ls())
library(tidyverse)
library(conflicted)
library(tictoc)     # timing
```


https://en.wikipedia.org/wiki/Triangular_distribution

$$
f(x | a, b, c) = 
\begin{cases}
  0                         & \text{se} \; x < a \\
  \frac{2(x-a)}{(b-a)(c-a)} & \text{se} \; a \leq x < c \\
  \frac{2}{b-a}             & \text{se} \; x = c \\
  \frac{2(b-x)}{(b-a)(b-c)} & \text{se} \; c < x \leq b \\
  0                         & \text{se} \; x > b
\end{cases}
$$

```{r distribuição-triangular}
dtriang <- function(x, a = 0, b = 1, c= 0.5) {
  # a -> min, b -> max, c -> mode
  data.table::fcase(
    x < a | x > b    , 0,
    x <= c           , 2 * (x - a) / ((b - a) * (c - a)),
    x > c            , 2 * (b - x) / ((b - a) * (b - c)),
    TRUE             , NA_real_
  )
}
extraDistr::dtriang(1:10,1,10,3)
dtriang(1:10,1,10,3)
```

```{r}
dtest <- \(x) {
  if(x < 0 | x > 1) return(0)
  (3/2)*x^3 + (11/8)*x^2 + (1/6)*x + 1/12
}

aceitacao_rejeicao_triang <- function(n, a = 0, b = 1, c = 0.5, seed = 2023) {
  set.seed(seed)
  f <- \(x) dtriang(x, a, b, c)
  # proposed function
  g <- \(x) dunif(x, a, b)
  # x (random variable) generator 
  X <- \() runif(1, a, b)
  # c: max of f, so that c >= f(x) / g(x) for all x
  C <- (f(c)/g(c)) ## o maximo da funcao triangular e no dtriang(c)
  # monte carlo (u(0, 1) <= f(x) / (c*g(x)) <=> u(0, c*g(x)) <= f(x))
  U <- \() runif(n=1, min=0, max=1)
  ret <- c()
  while(length(ret) < n) {
    u <- U()
    x <- X()
    if (u <= f(x) / (C*g(x)))
      ret <- c(ret, x)
  }
  ret
}
rtriang <- aceitacao_rejeicao_triang

aceitacao_rejeicao_test <- function(n) {
  f <- dtest
  # proposed function
  g <- dunif
  # x (random variable) generator 
  X <- \() runif(1)
  # c: max of f, so that c >= f(x) / g(x) for all x
  C <- f(1) ## o maximo da funcao triangular e no dtriang(c)
  # monte carlo (u(0, 1) <= f(x) / (c*g(x)) <=> u(0, c*g(x)) <= f(x))
  u <- \(x) runif(n=1, min=0, max=1)
  
  ret <- c()
  while(length(ret) < n) {
    x <- X()
    if (u(x) <= f(x) / (C*g(x)))
      ret <- c(ret, x)
  }
  ret
}
```

```{r plots}
set.seed(2023)
tic()
  generated <- rtriang(10000, 0, 100, 50)
toc()
generated %>% head()
```

```{r}
# Agora bonito
ggplot(tibble(x = generated), aes(x)) + 
  geom_histogram(aes(y = after_stat(density)), bins = 20, colour = "black", fill = "white") +
  geom_density(aes(color = "observado"), kernel = "gaussian", linewidth = 1, fill = "#F73859", alpha = 0.4) + 
  stat_function(aes(color = "teorico"), fun = dtriang, args = list(a = 1, b = 100, c = 50), linewidth = 1) +
  labs(title = "Distribuição triangular gerada (a = 0, b = 100, c = 50)", x = "x", y = "Densidade") +
  scale_colour_manual("", values = c("observado" = "#F73859", "teorico" = "#404B69"), guide = guide_legend())
```


```{r}
# a = 0, b = 100 e c = 50
ggplot(tibble(x = generated), aes(x)) + 
  geom_histogram(aes(y = after_stat(density)), bins = 20, colour = "black", fill = "white") +
  geom_density(color = "#F73859", kernel = "gaussian", linewidth = 1, fill = "#F73859", alpha = 0.25) + 
  stat_function(fun = dtriang, args = list(a = 0, b = 100, c = 50), color = "#404B69", linewidth = 1) +
  labs(title = "Distribuição triangular gerada (a = 0, b = 100, c = 50)", x = "x", y = "Densidade")
# a = 0, b = 10 e c = 5
generated2 <- rtriang(10000, 0, 10, 5)
ggplot(tibble(x = generated2), aes(x)) + 
  geom_histogram(aes(y = after_stat(density)), bins = 20, colour = "black", fill = "white") +
  geom_density(color = "#F73859", kernel = "gaussian", linewidth = 1, fill = "#F73859", alpha = 0.25) + 
  stat_function(fun = dtriang, args = list(a = 0, b = 10, c = 5), color = "#404B69", linewidth = 1) +
  labs(title = "Distribuição triangular gerada (a = 0, b = 10, c = 5)", x = "x", y = "Densidade")
# a = 1, b = 2, c = 1.2
generated3 <- rtriang(10000, 1, 2, 1.2)
ggplot(tibble(x = generated3), aes(x)) + 
  geom_histogram(aes(y = after_stat(density)), bins = 20, colour = "black", fill = "white") +
  geom_density(color = "#F73859", kernel = "gaussian", linewidth = 1, fill = "#F73859", alpha = 0.25) + 
  stat_function(fun = dtriang, args = list(a = 1, b = 2, c = 1.2), color = "#404B69", linewidth = 1) +
  labs(title = "Distribuição triangular gerada (a = 1, b = 2, c = 1.2)", x = "x", y = "Densidade")
# a = 1, b = 100, c = 70
generated4 <- rtriang(10000, 1, 100, 70)
ggplot(tibble(x = generated4), aes(x)) + 
  geom_histogram(aes(y = after_stat(density)), bins = 20, colour = "black", fill = "white") +
  geom_density(color = "#F73859", kernel = "gaussian", linewidth = 1, fill = "#F73859", alpha = 0.25) + 
  stat_function(fun = dtriang, args = list(a = 1, b = 100, c = 70), color = "#404B69", linewidth = 1) +
  labs(title = "Distribuição triangular gerada (a = 1, b = 100, c = 70)", x = "x", y = "Densidade")

```


```{r}
# data frame com estatisticas teoricas e observadas

mean_triang <- \(a, b, c) (a + b + c) / 3
median_triang <- \(a, b, c) (2*c + b - a) / 4
variance_triang <- \(a, b, c) (a^2 + b^2 + c^2 - a*b - a*c - b*c) / 18
tribble(
  ~desc, ~mean, ~median, ~variance,
  "Teórico (a = 0, b = 100, c = 50)", mean_triang(0, 100, 50), median_triang(0, 100, 50), variance_triang(0, 100, 50),
  "Observado (a = 0, b = 100, c = 50)", mean(generated), median(generated), var(generated),
  "Teórico (a = 0, b = 10, c = 5)", mean_triang(0, 10, 5), median_triang(0, 10, 5), variance_triang(0, 10, 5),
  "Observado (a = 0, b = 10, c = 5)", mean(generated2), median(generated2), var(generated2),
  "Teórico (a = 1, b = 2, c = 1.2)", mean_triang(1, 2, 1.2), median_triang(1, 2, 1.2), variance_triang(1, 2, 1.2),
  "Observado (a = 1, b = 2, c = 1.2)", mean(generated3), median(generated3), var(generated3),
  "Teórico (a = 1, b = 100, c = 70)", mean_triang(1, 100, 70), median_triang(1, 100, 70), variance_triang(1, 100, 70),
  "Observado (a = 1, b = 100, c = 70)", mean(generated4), median(generated4), var(generated4)
) -> stats
stats
stats %>% knitr::kable( digits = 3, caption = "Estatísticas teóricas e observadas" )
```


```{r}
## generate points
# a = 1, b = 100, c = 50
aceitacao_rejeicao_points <- function(n, a, b, c) {
  f <- \(x) dtriang(x, a, b, c)
  # proposed function
  g <- \(x) dunif(x, a, b)
  # x (random variable) generator 
  X <- \() runif(1, a, b)
  # c: max of f, so that c >= f(x) / g(x) for all x
  C <- (f(c)/g(c)) ## o maximo da funcao triangular e no dtriang(c)
  # monte carlo (u(0, 1) <= f(x) / (c*g(x)) <=> u(0, c*g(x)) <= f(x))
  U <- \() runif(n=1, min=0, max=1)
  points <- tibble(x = numeric(0), y = numeric(0), accepted = factor(0))
  for(i in 1:n) {
    x <- X()
    u <- U()
    if(u <= f(x) / (C*g(x))) {
      points <- points %>% add_row(x = x, y = u, accepted = "Aceitado")
    } else {
      points <- points %>% add_row(x = x, y = u, accepted = "Rejeitado")
    }
  }
  return(points)
}
set.seed(2023)
ggplot(aceitacao_rejeicao_points(10000, 0, 100, 50), aes(x, y)) +
  geom_point(aes(color = accepted), alpha = 0.5) +
  labs(title = "10000 Pontos gerados (0, 100, 50)", x = "x", y = "u") +
  scale_color_manual(values = c("Aceitado" = "#F73859", "Rejeitado" = "#404B69")) +
  theme(legend.position = "none")
```

```{r}
## draw f(x), g(x) and f(x)/g(x), f being dtriang and g being dunif
# a = 1, b = 100, c = 50
a <- 1
b <- 100
c <- 50
f <- \(x) dtriang(x, a, b, c)
g <- \(x) dunif(x, a, b)
plot(f, from = a, to = b, col = "#F73859", main = "f(x), g(x) and f(x)/g(x)", xlab = "x", ylab = "y")
plot(g, from = a, to = b, col = "#404B69", add = T)
plot(\(x) f(x)/g(x), from = a, to = b, col = "#404B69", lty = 2, add = T)
legend("topright", legend = c("f(x)", "g(x)", "f(x)/g(x)"), col = c("#F73859", "#404B69", "#404B69"), lty = c(1, 1, 2))
```

